# Generated by Django 4.2.2 on 2023-08-17 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=150, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrderTelegtam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('quantity', models.IntegerField()),
                ('item_sku', models.TextField(verbose_name='Артикул товара')),
                ('item_color', models.TextField(verbose_name='Color')),
                ('item_size', models.TextField(verbose_name='Размер товара')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photowh', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.status')),
            ],
            options={
                'verbose_name': 'ЗаказОптом',
                'verbose_name_plural': 'ЗаказыОптом',
            },
        ),
        migrations.CreateModel(
            name='RetailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('sku', models.CharField(max_length=255, verbose_name='Артикул товара')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет товара')),
                ('size', models.CharField(max_length=255, verbose_name='Размер товара')),
                ('amount', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('unique_idwh', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный IDwh')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.status')),
            ],
            options={
                'verbose_name': 'ТоварРозницу',
                'verbose_name_plural': 'ТоварРозницу',
            },
        ),
    ]
