# Generated by Django 4.2.2 on 2023-08-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailorder',
            old_name='unique_idwh',
            new_name='id_wh',
        ),
    ]
