# Generated by Django 4.2.2 on 2023-07-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('sku', models.CharField(max_length=255, verbose_name='Артикул товара')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет товара')),
                ('colorb', models.CharField(max_length=255, verbose_name='Цвет товара Б/У')),
                ('size', models.CharField(max_length=255, verbose_name='Размер товара')),
                ('amount', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.status')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
