# Generated by Django 4.2.2 on 2023-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_rename_unique_idwh_retailorder_id_wh'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
