# Generated by Django 4.2.2 on 2023-07-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_wholesale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Имя пользователя')),
                ('quantity', models.IntegerField()),
                ('item_sku', models.TextField(verbose_name='Артикул товара')),
                ('item_color', models.TextField(verbose_name='Color')),
                ('item_size', models.TextField(verbose_name='Размер товара')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.BinaryField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.status')),
            ],
        ),
    ]
